import { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

const Company = ({company}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Codat X Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Next.js</a> X <a href="https://www.codat.io">Codat!</a>
        </h1>

        <p>
          This page uses 
          <a href="https://nextjs.org/docs/basic-features/pages#server-side-rendering">Server-side Rendering</a>, 
          and is rendered server side every time the page is requested.
          This ensures your Codat API key is not exposed to the user.
        </p>

        <h2>{company.name}</h2>
        <p><i>{company.id}</i></p>
        <p><b>Connections:</b> {company.platform}</p>
        <p><b>Last pull:</b> {company.lastSync}</p>
        <p><b>Created:</b> {company.created}</p>

        <br/>

        <div className={styles.grid}>
          <a className={styles.card} href={`https://app.codat.io/companies/${company.id}`} target="_blank" rel="noreferrer">
            Explore {company.name} in the Portal →
          </a>

          <Link key={company.id} href={`/`} className={styles.card}>
            <p className={styles.card}>← Back to Home</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const companyId = context.params.id[0];

  // Encode your API key
  const encodedKey = Buffer.from(process.env.CODAT_API_KEY).toString(
    "base64"
  );

  // Add auth to the headers
  const headers = {
    method: "GET",
    headers: {
      authorization: "Basic " + encodedKey,
      "Access-Control-Allow-Origin": "*",
    },
  }

  // Fetch data from external API
  const res = await fetch(`https://api.codat.io/companies/${companyId}`, headers)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { company: data } }
}


export default Company;