import Head from 'next/head'
import Link from 'next/link';

import styles from './page.module.css'

import { CodatCommon } from "@codat/common";
import { ListCompaniesResponse } from "@codat/common/dist/sdk/models/operations";

export const revalidate = 60;

const common = new CodatCommon({
  security: {
    authHeader: process.env.CODAT_AUTH_HEADER!,
  },
});

const getData = async () => {
  const res = await common.companies
    .list({
      page: 1,
      pageSize: 100,
    })
    .then((res: ListCompaniesResponse) => {
      if (res.statusCode == 200) {
        return res
      }

      throw new Error("Companies not found")
    });

  return res.companies;
}

const Home = async () => {
  const companies = await getData();

  return (
    <main className={styles.main}>
      <Head>
        <title>Codat X Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>app/page.tsx</code>
        </p>
        <div>
          <a
            href="https://github.com/codatio/starter-project-nextjs-codat"
            target="_blank"
            rel="noopener noreferrer"
          >
            starter-project-nextjs-codat
          </a>
        </div>
      </div>

      <h1 className={styles.center}>Codat X Next.js</h1>

      <p>
        This page uses 
        <a href="https://nextjs.org/docs/basic-features/pages#server-side-rendering">Server-side Rendering</a>, 
        and is rendered server side every time the page is requested.
        This ensures your Codat API key is not exposed to the user.
      </p>

      <h2 className={styles.center}>Companies</h2>

      <div className={styles.grid}>
        {
          companies?.results?.length! >= 1
            ? companies?.results?.map(company => {
              return <Link key={company.id} href={`/companies/${company.id}`} className={styles.card}>
                <h4>
                  {company.name} <span>-&gt;</span>
                </h4>
              </Link>
            })
            : <div className={styles.card}>
                <h2>No companies</h2>
                <p>Head to the <a href="https://app.codat.io/companies" target="_blank" rel="noreferrer">Codat Portal</a> to add your first company</p>
              </div>
        }
      </div>

      <hr className={styles.hr}/>

      <div className={styles.grid}>
        <a
          href="https://beta.nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Docs <span>-&gt;</span>
          </h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Learn <span>-&gt;</span>
          </h2>
          <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
        </a>

        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Templates <span>-&gt;</span>
          </h2>
          <p>Explore the Next.js 13 playground.</p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>
            Deploy <span>-&gt;</span>
          </h2>
          <p>
            Instantly deploy your Next.js site to a shareable URL with Vercel.
          </p>
        </a>
      </div>
    </main>
  )
}

export default Home;